title: David Wise
description: Technologies, startups, idées, livres.

url: http://brianmaierjr.github.com/long-haul
baseurl: "/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Accueil
   url: /index.html
 - title: A Propos
   url: /about
 - title: Outils
   url: /outils
 - title: Startups
   url: /startups
 - title: Livres
   url: /bibliotheque

social:
   twitter: dawise_
   facebook: brianmaierjr
   email: hello@davidwise.fr 

google_analytics: "UA-58263416-1"