title: David Wise
description: J'aime les idées et les technologies. Dans cet ordre.

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: About
   url: /about
 - title: Outils
   url: /outils
 - title: Contact
   url: /contact

social:
   twitter: dawise_
   facebook: brianmaierjr
   email: hello@davidwise.fr 

google_analytics: "UA-58263416-1"