title: David Wise
description: Humanités, technologies, entrepreneuriat, education.

url: http://www.davidwise.fr
baseurl: ""
paginate_path: "/page:num/"
permalink: /:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: A Propos
   url: /apropos
 - title: Outils
   url: /outils
 - title: Bibliotheque
   url: /bibliotheque
 - title: Cours
   url: /cours

social:
   twitter: dawise_
   facebook: 
   email: hello@davidwise.fr 

google_analytics: "UA-58263416-1"